name: Update AWS Services List

on:
  schedule:
    - cron: '0 15 * * *' # UTC表示, JSTは9時間進んでいる
  workflow_dispatch:

jobs:
  update_aws_services:
    runs-on: ubuntu-latest
    env:
      ARTICLE_PATH="articles/aws-ipaddresses-services.md"

    steps:
      - name: Fetch AWS Services List
        id: fetch_services
        run: |
          SERVICES=$(curl -s https://ip-ranges.amazonaws.com/ip-ranges.json | jq -r '.prefixes[].service' | sort -u)
          echo "$SERVICES" > new_services_list.txt
      
      - name: Check for services list changes
        id: check_changes
        run: |
          sed -n '/<!-- AWS_SERVICES_LIST_START -->/,/<!-- AWS_SERVICES_LIST_END -->/p' "${{ env.ARTICLE_PATH }}" | sed '/```/d' | sed '/<!--.*-->/d' > current_services_list.txt

          if ! diff -q current_services_list.txt new_services_list.txt > /dev/null; then
            echo "Services list has changed."
            echo "services_changed_flag=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in AWS services list."
            echo "services_changed_flag=false" >> $GITHUB_OUTPUT
          fi


          

