name: Update AWS Services List

on:
  schedule:
    - cron: 0 15 * * * #JST 0:00
  workflow_dispatch:

jobs:

  update_aws_services:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install requests

      - name: Run AWS services update script
        working-directory: scripts
        env:
          TZ: 'Asia/Tokyo'
        run: |
          python update-aws-services-in-article.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update AWS services list"
          git push
