name: Update AWS Services List

on:
  push:
    branches:
      - feature/aws-ipaddresses-services
  workflow_dispatch:

jobs:
  update_aws_services:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install requests

      - name: Run AWS services update script
        working-directory: scripts
        run: |
          python update-aws-services-in-article.py
        env:
          GITHUB_ENV: $GITHUB_ENV

      - name: Commit and push changes
        if: env.UPDATE_REQUIRED == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update AWS services list"
          git push

      - name: Notify on error
        if: env.ERROR_OCCURRED == 'true'
        run: echo "An error occurred in the script execution."
